apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: smoke-pod-kill
  namespace: chaos-lab
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - chaos-lab
    labelSelectors:
      app: sre-demo-payment
